// OpenAI integration for generating PDF report content using GPT-5
// Reference: javascript_openai_ai_integrations blueprint
import OpenAI from "openai";
import type { PdfReportData } from "@shared/schema";

// the newest OpenAI model is "gpt-5" which was released August 7, 2025. do not change this unless explicitly requested by the user
const openai = new OpenAI({
  baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
  apiKey: process.env.AI_INTEGRATIONS_OPENAI_API_KEY,
});

export async function generateReportMarkdown(reportData: PdfReportData): Promise<string> {
  const prompt = `You are generating a professional PDF report for the A-Team Trades Pipeline™ diagnostic.

Builder Information:
- Name: ${reportData.builderName || "Builder"}
- Email: ${reportData.email}
- Overall Score: ${reportData.overallScore}/100 (${reportData.scoreColor.toUpperCase()})

Section Scores:
${Object.entries(reportData.sectionScores)
  .map(
    ([key, section]) =>
      `- ${key}: ${section.score}/10 (${section.color.toUpperCase()}) - ${section.commentary}`
  )
  .join("\n")}

Top Recommendations:
${reportData.topRecommendations
  .map((rec, i) => `${i + 1}. ${rec.title}: ${rec.explanation} (Impact: ${rec.impact})`)
  .join("\n")}

Risk Profile: ${reportData.riskProfile.color.toUpperCase()} - ${reportData.riskProfile.explanation}

Labour Leak Projection:
- Annual Leak: ${reportData.labourLeakProjection.annualLeak}
- Improvement Range: ${reportData.labourLeakProjection.improvementRange}
- Time Horizon: ${reportData.labourLeakProjection.timeHorizon}

Generate a professional, detailed Markdown report with the following structure:

# A-Team Trades Pipeline™ Score Report

**Your Personalised Labour Pipeline Diagnostic**

**Builder:** ${reportData.builderName || "Builder"}  
**Date:** ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

---

## Executive Summary

[Write a personalized 2-3 paragraph summary explaining what the overall score means, the 3 biggest issues, and the potential impact]

---

## Your Overall Score: ${reportData.overallScore}/100

**Status:** ${reportData.scoreColor === "green" ? "EXCELLENT" : reportData.scoreColor === "amber" ? "MODERATE RISK" : "CRITICAL"}

[Explain what this score means in practical terms for their business]

---

## Section Breakdown

[For each section, create a detailed section with score, traffic light indicator, and detailed commentary]

---

## Top 5 Recommended Fixes

[Expand on each recommendation with actionable steps and expected impact]

---

## Labour Risk Profile

**Risk Level:** ${reportData.riskProfile.color.toUpperCase()}

[Detailed explanation of the risk profile and what it means]

---

## Projected Labour Leak

**Estimated Annual Loss:** ${reportData.labourLeakProjection.annualLeak}

[Detailed breakdown of how this leak manifests and what can be recovered]

---

## Next Steps

If you want help fixing these labour leaks and improving your score, book a free Freedom Roadmap Call with Greg.

**Book Your Call:** https://developcoaching.co.uk/schedule-a-call

---

*Report generated by A-Team Trades Pipeline™ GPT  
Powered by Develop Coaching*

Make this report professional, actionable, and motivating. Use UK English spelling and terminology appropriate for UK builders.`;

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-5", // the newest OpenAI model is "gpt-5" which was released August 7, 2025. do not change this unless explicitly requested by the user
      messages: [
        {
          role: "system",
          content:
            "You are an expert business consultant specializing in UK construction and trades businesses. Generate professional, actionable PDF reports that help builders identify and fix labour pipeline issues.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      max_completion_tokens: 8192,
    });

    const markdown = response.choices[0]?.message?.content || "";
    return markdown;
  } catch (error) {
    console.error("[OpenAI] Error generating report markdown:", error);
    throw new Error("Failed to generate report content");
  }
}
