// OpenAI integration for generating PDF report content using GPT-4o-mini
// Fast, cost-effective, and reliable for generating professional reports
import OpenAI from "openai";
import type { PdfReportData } from "@shared/schema";

// Using GPT-4o-mini for fast and cost-effective report generation
const openai = new OpenAI({
  baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
  apiKey: process.env.AI_INTEGRATIONS_OPENAI_API_KEY,
});

// Fallback markdown generator if OpenAI fails or times out
function generateFallbackMarkdown(reportData: PdfReportData): string {
  const statusText = reportData.scoreColor === "green" ? "EXCELLENT" : reportData.scoreColor === "amber" ? "MODERATE RISK" : "CRITICAL";
  
  return `# A-Team Trades Pipeline™ Score Report

**Your Personalised Labour Pipeline Diagnostic**

**Builder:** ${reportData.builderName || "Builder"}  
**Date:** ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

---

## Executive Summary

Your overall pipeline score is **${reportData.overallScore}/100** (${statusText}). This report provides a detailed analysis of your labour pipeline and identifies key areas for improvement to help you attract, manage, and retain reliable labour.

Based on your diagnostic, we've identified several opportunities to strengthen your pipeline and reduce labour leaks. The recommendations in this report could help you recover **${reportData.labourLeakProjection.improvementRange}** over the next **${reportData.labourLeakProjection.timeHorizon}**.

---

## Your Overall Score: ${reportData.overallScore}/100

**Status:** ${statusText}

${
  reportData.scoreColor === "green"
    ? "Your labour pipeline is in good health. Focus on maintaining these strong systems while addressing the improvement areas highlighted below."
    : reportData.scoreColor === "amber"
      ? "Your pipeline shows moderate risk. There are clear opportunities to improve reliability and reduce labour costs through better systems."
      : "Your pipeline requires immediate attention. The gaps identified are likely costing you significant time and money through unreliable labour."
}

---

## Section Breakdown

${Object.entries(reportData.sectionScores)
  .map(
    ([key, section]) => `### ${key.replace(/([A-Z])/g, " $1").trim()}

**Score:** ${section.score}/10 (${section.color.toUpperCase()})

${section.commentary}

${
  section.color === "red"
    ? "⚠️ **Priority Area** - This requires immediate attention to prevent further labour issues."
    : section.color === "amber"
      ? "⚡ **Improvement Opportunity** - Strengthening this area will significantly improve your pipeline."
      : "✅ **Strength** - Continue maintaining this aspect of your pipeline."
}
`
  )
  .join("\n")}

---

## Top Recommended Fixes

${reportData.topRecommendations
  .map(
    (rec, i) => `### ${i + 1}. ${rec.title}

${rec.explanation}

**Potential Impact:** ${rec.impact}
`
  )
  .join("\n")}

---

## Labour Risk Profile

**Risk Level:** ${reportData.riskProfile.color.toUpperCase()}

${reportData.riskProfile.explanation}

---

## Projected Labour Leak

**Estimated Annual Loss:** ${reportData.labourLeakProjection.annualLeak}

Without addressing these pipeline gaps, you're likely losing **${reportData.labourLeakProjection.annualLeak}** annually through:
- Unreliable subcontractors causing delays
- Last-minute labour cancellations
- Paying over the odds for emergency labour
- Time wasted chasing and managing unreliable teams

By implementing the recommended fixes, you could recover **${reportData.labourLeakProjection.improvementRange}** over the next **${reportData.labourLeakProjection.timeHorizon}**.

---

## Next Steps

If you want help fixing these labour leaks and improving your score, book a free Freedom Roadmap Call with Greg.

**Book Your Call:** https://developcoaching.co.uk/schedule-a-call

---

*Report generated by A-Team Trades Pipeline™  
Powered by Develop Coaching*`;
}

export async function generateReportMarkdown(reportData: PdfReportData): Promise<string> {
  console.log("[OpenAI] Generating report markdown for:", reportData.builderName);
  
  // Check if OpenAI is configured
  const hasApiKey = !!(process.env.AI_INTEGRATIONS_OPENAI_API_KEY && process.env.AI_INTEGRATIONS_OPENAI_BASE_URL);
  
  if (!hasApiKey) {
    console.warn("[OpenAI] API keys not configured - using fallback markdown generator");
    return generateFallbackMarkdown(reportData);
  }

  const prompt = `You are generating a professional PDF report for the A-Team Trades Pipeline™ diagnostic.

Builder Information:
- Name: ${reportData.builderName || "Builder"}
- Email: ${reportData.email}
- Overall Score: ${reportData.overallScore}/100 (${reportData.scoreColor.toUpperCase()})

Section Scores:
${Object.entries(reportData.sectionScores)
  .map(
    ([key, section]) =>
      `- ${key}: ${section.score}/10 (${section.color.toUpperCase()}) - ${section.commentary}`
  )
  .join("\n")}

Top Recommendations:
${reportData.topRecommendations
  .map((rec, i) => `${i + 1}. ${rec.title}: ${rec.explanation} (Impact: ${rec.impact})`)
  .join("\n")}

Risk Profile: ${reportData.riskProfile.color.toUpperCase()} - ${reportData.riskProfile.explanation}

Labour Leak Projection:
- Annual Leak: ${reportData.labourLeakProjection.annualLeak}
- Improvement Range: ${reportData.labourLeakProjection.improvementRange}
- Time Horizon: ${reportData.labourLeakProjection.timeHorizon}

Generate a professional, detailed Markdown report with the following structure:

# A-Team Trades Pipeline™ Score Report

**Your Personalised Labour Pipeline Diagnostic**

**Builder:** ${reportData.builderName || "Builder"}  
**Date:** ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

---

## Executive Summary

[Write a personalized 2-3 paragraph summary explaining what the overall score means, the 3 biggest issues, and the potential impact]

---

## Your Overall Score: ${reportData.overallScore}/100

**Status:** ${reportData.scoreColor === "green" ? "EXCELLENT" : reportData.scoreColor === "amber" ? "MODERATE RISK" : "CRITICAL"}

[Explain what this score means in practical terms for their business]

---

## Section Breakdown

[For each section, create a detailed section with score, traffic light indicator, and detailed commentary]

---

## Top Recommended Fixes

[Expand on each recommendation with actionable steps and expected impact]

---

## Labour Risk Profile

**Risk Level:** ${reportData.riskProfile.color.toUpperCase()}

[Detailed explanation of the risk profile and what it means]

---

## Projected Labour Leak

**Estimated Annual Loss:** ${reportData.labourLeakProjection.annualLeak}

[Detailed breakdown of how this leak manifests and what can be recovered]

---

## Next Steps

If you want help fixing these labour leaks and improving your score, book a free Freedom Roadmap Call with Greg.

**Book Your Call:** https://developcoaching.co.uk/schedule-a-call

---

*Report generated by A-Team Trades Pipeline™  
Powered by Develop Coaching*

Make this report professional, actionable, and motivating. Use UK English spelling and terminology appropriate for UK builders.`;

  try {
    console.log("[OpenAI] Calling GPT-4o-mini API...");

    // Add timeout to OpenAI call (45 seconds)
    const timeoutPromise = new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error("OpenAI request timed out after 45 seconds")), 45000)
    );

    const apiPromise = openai.chat.completions.create({
      model: "gpt-4o-mini", // Fast, cost-effective GPT-4 model for report generation
      messages: [
        {
          role: "system",
          content:
            "You are an expert business consultant specializing in UK construction and trades businesses. Generate professional, actionable PDF reports in Markdown format that help builders identify and fix labour pipeline issues. Use UK English spelling. Be specific, practical, and motivating.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.7,
      max_completion_tokens: 4096,
    });

    const response = await Promise.race([apiPromise, timeoutPromise]);

    const markdown = response.choices[0]?.message?.content || "";
    console.log("[OpenAI] Successfully generated markdown (" + markdown.length + " chars)");
    return markdown;
  } catch (error: any) {
    console.error("[OpenAI] Error generating report markdown:", error.message);
    
    // Fall back to template-based generation
    console.warn("[OpenAI] Falling back to template-based report generation");
    return generateFallbackMarkdown(reportData);
  }
}
