// OpenAI integration for generating PDF report content using GPT-4o-mini
// Fast, cost-effective, and reliable for generating professional reports
import OpenAI from "openai";
import type { PdfReportData } from "@shared/schema";

// Using GPT-4o-mini for fast and cost-effective report generation
const openai = new OpenAI({
  baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
  apiKey: process.env.AI_INTEGRATIONS_OPENAI_API_KEY,
});

// Fallback markdown generator if OpenAI fails or times out
function generateFallbackMarkdown(reportData: PdfReportData): string {
  const statusText = reportData.scoreColor === "green" ? "EXCELLENT" : reportData.scoreColor === "amber" ? "MODERATE RISK" : "CRITICAL";
  
  return `# A-Team Trades Pipeline™ Score Report

**Your Personalised Labour Pipeline Diagnostic**

**Builder:** ${reportData.builderName || "Builder"}  
**Date:** ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

---

## Executive Summary

Your overall pipeline score is **${reportData.overallScore}/100** (${statusText}). This report provides a detailed analysis of your labour pipeline and identifies key areas for improvement to help you attract, manage, and retain reliable labour.

Based on your diagnostic, we've identified several opportunities to strengthen your pipeline and reduce labour leaks. The recommendations in this report could help you recover **${reportData.labourLeakProjection.improvementRange}** over the next **${reportData.labourLeakProjection.timeHorizon}**.

---

## Your Overall Score: ${reportData.overallScore}/100

**Status:** ${statusText}

${
  reportData.scoreColor === "green"
    ? "Your labour pipeline is in good health. Focus on maintaining these strong systems while addressing the improvement areas highlighted below."
    : reportData.scoreColor === "amber"
      ? "Your pipeline shows moderate risk. There are clear opportunities to improve reliability and reduce labour costs through better systems."
      : "Your pipeline requires immediate attention. The gaps identified are likely costing you significant time and money through unreliable labour."
}

---

## Section Breakdown

${Object.entries(reportData.sectionScores)
  .map(
    ([key, section]) => `### ${key.replace(/([A-Z])/g, " $1").trim()}

**Score:** ${section.score}/10 (${section.color.toUpperCase()})

${section.commentary}

${
  section.color === "red"
    ? "⚠️ **Priority Area** - This requires immediate attention to prevent further labour issues."
    : section.color === "amber"
      ? "⚡ **Improvement Opportunity** - Strengthening this area will significantly improve your pipeline."
      : "✅ **Strength** - Continue maintaining this aspect of your pipeline."
}
`
  )
  .join("\n")}

---

## Top Recommended Fixes

${reportData.topRecommendations
  .map(
    (rec, i) => `### ${i + 1}. ${rec.title}

${rec.explanation}

**Potential Impact:** ${rec.impact}
`
  )
  .join("\n")}

---

## Labour Risk Profile

**Risk Level:** ${reportData.riskProfile.color.toUpperCase()}

${reportData.riskProfile.explanation}

---

## Projected Labour Leak

**Estimated Annual Loss:** ${reportData.labourLeakProjection.annualLeak}

Without addressing these pipeline gaps, you're likely losing **${reportData.labourLeakProjection.annualLeak}** annually through:
- Unreliable subcontractors causing delays
- Last-minute labour cancellations
- Paying over the odds for emergency labour
- Time wasted chasing and managing unreliable teams

By implementing the recommended fixes, you could recover **${reportData.labourLeakProjection.improvementRange}** over the next **${reportData.labourLeakProjection.timeHorizon}**.

---

## Next Steps

If you want help fixing these labour leaks and improving your score, book a free Freedom Roadmap Call with Greg.

**Book Your Call:** https://developcoaching.co.uk/schedule-a-call

---

*Report generated by A-Team Trades Pipeline™  
Powered by Develop Coaching*`;
}

export async function generateReportMarkdown(reportData: PdfReportData): Promise<string> {
  console.log("[OpenAI] Generating report markdown for:", reportData.builderName);
  console.log("[OpenAI] Report data received:", JSON.stringify({
    email: reportData.email,
    builderName: reportData.builderName,
    overallScore: reportData.overallScore,
    scoreColor: reportData.scoreColor,
    sectionCount: Object.keys(reportData.sectionScores).length,
    recommendationsCount: reportData.topRecommendations.length
  }, null, 2));

  // Check if OpenAI is configured
  const hasApiKey = !!(process.env.AI_INTEGRATIONS_OPENAI_API_KEY && process.env.AI_INTEGRATIONS_OPENAI_BASE_URL);

  if (!hasApiKey) {
    console.warn("[OpenAI] API keys not configured - using fallback markdown generator");
    return generateFallbackMarkdown(reportData);
  }

  const prompt = `Generate a professional PDF report for ${reportData.builderName}, a UK builder/contractor who just completed the A-Team Trades Pipeline™ diagnostic.

KEY DATA:
Overall Score: ${reportData.overallScore}/100 (${reportData.scoreColor === "green" ? "GREEN - Good" : reportData.scoreColor === "amber" ? "AMBER - Moderate Risk" : "RED - Critical Issues"})

Section Performance:
${Object.entries(reportData.sectionScores)
  .map(([key, section]) => `- ${key.replace(/([A-Z])/g, " $1").trim()}: ${section.score}/10 (${section.color.toUpperCase()}) - ${section.commentary}`)
  .join("\n")}

Top 3 Issues: ${reportData.topRecommendations.map((r, i) => `${i + 1}) ${r.title}`).join(", ")}

Estimated Annual Labour Leak: ${reportData.labourLeakProjection.annualLeak}
Potential Savings: ${reportData.labourLeakProjection.improvementRange} (within ${reportData.labourLeakProjection.timeHorizon})

INSTRUCTIONS:
Write a compelling, specific, personalized report in Markdown format using this EXACT structure:

# A-Team Trades Pipeline™ Score Report

**Your Personalised Labour Pipeline Diagnostic**

**Builder:** ${reportData.builderName || "Builder"}
**Date:** ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}

---

## Executive Summary

[2-3 punchy paragraphs that: 1) Acknowledge their current situation based on their score, 2) Highlight the 2-3 biggest pain points they're facing, 3) Quantify the money/time they're losing, 4) Give them hope with the potential savings]

---

## Your Overall Score: ${reportData.overallScore}/100

**Status:** ${reportData.scoreColor === "green" ? "EXCELLENT" : reportData.scoreColor === "amber" ? "MODERATE RISK" : "CRITICAL"}

[1-2 paragraphs explaining what this score means in plain English - use examples like "If you're juggling 6-8 projects, unreliable subbies are probably costing you..."]

---

## Section Breakdown

${Object.entries(reportData.sectionScores)
  .map(
    ([key, section]) => `### ${key.replace(/([A-Z])/g, " $1").trim()}

**Score:** ${section.score}/10 (${section.color.toUpperCase()})

${section.commentary}

${section.color === "red" ? "⚠️ **Priority Area** - This requires immediate attention." : section.color === "amber" ? "⚡ **Improvement Opportunity** - Quick wins available here." : "✅ **Strength** - Keep doing what you're doing."}`
  )
  .join("\n\n")}

---

## Top 3 Recommended Fixes

${reportData.topRecommendations
  .map(
    (rec, i) => `### ${i + 1}. ${rec.title}

**What to do:** ${rec.explanation}

**Potential Impact:** ${rec.impact}

**Why it matters:** [Add 1-2 sentences explaining the real-world impact - delays avoided, cash saved, stress reduced, etc.]`
  )
  .join("\n\n")}

---

## Your Labour Leak Projection

**You're currently losing:** ${reportData.labourLeakProjection.annualLeak} per year

This leak comes from:
- No-shows and last-minute cancellations causing project delays
- Paying premium rates for emergency labour
- Time wasted chasing unreliable subbies
- Projects running over budget due to labour issues

**The Good News:** By implementing the fixes above, you could recover **${reportData.labourLeakProjection.improvementRange}** within the next **${reportData.labourLeakProjection.timeHorizon}**.

---

## Next Steps

If you want help fixing these labour leaks and building a reliable pipeline, book a free Scale Session call with our team.

**Book Your Call:** https://developcoaching.co.uk/schedule-a-call

---

*Report generated by A-Team Trades Pipeline™
Powered by Develop Coaching*

STYLE GUIDELINES:
- Use UK English (labour, not labor; organise, not organize)
- Be conversational but professional - talk like a business advisor, not a salesperson
- Use specific examples relevant to UK builders (subbies, trades, projects, etc.)
- Keep paragraphs short (2-4 sentences max)
- Focus on practical, actionable insights - no fluff
- Make them feel understood, then show them the path forward`;

  try {
    console.log("[OpenAI] Calling GPT-4o-mini API...");

    // Add timeout to OpenAI call (45 seconds)
    const timeoutPromise = new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error("OpenAI request timed out after 45 seconds")), 45000)
    );

    const apiPromise = openai.chat.completions.create({
      model: "gpt-4o-mini", // Fast, cost-effective GPT-4 model for report generation
      messages: [
        {
          role: "system",
          content:
            "You are Greg from Develop Coaching, an expert advisor for UK builders and contractors. You understand the daily struggles of managing subbies, juggling projects, and dealing with unreliable labour. Write personalized, practical reports that make builders feel understood and show them a clear path to improvement. Use UK English. Be conversational but professional - like a trusted advisor, not a salesperson.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.7,
      max_completion_tokens: 4096,
    });

    const response = await Promise.race([apiPromise, timeoutPromise]);

    const markdown = response.choices[0]?.message?.content || "";
    console.log("[OpenAI] Successfully generated markdown (" + markdown.length + " chars)");
    return markdown;
  } catch (error: any) {
    console.error("[OpenAI] Error generating report markdown:", error.message);
    
    // Fall back to template-based generation
    console.warn("[OpenAI] Falling back to template-based report generation");
    return generateFallbackMarkdown(reportData);
  }
}
